### ISSUE TITLE
fn config_channels() missing from instrument instance

### ISSUE THREAD

**Issue by nanotechdave** [arc-instruments/pyarc2#1]
When calling 
```python
self.arc.config_channels()
```
from the run() function of the operation instance, an error occurs, saying that 'Instrument' does not have the config_channels() attribute. 

Ran on Windows 10 Pro, version 21H2

**Comment by foucault** [comment]
Hi! The `delay` and `config_channels` functions are not available on the 0.1 release of the library, so you will have to build `pyarc2` from git to get access to those. I'm currently in the middle of a rewrite on how the DAC commands are generated from the computer side and that's why I'm reluctant to publish a full new release before this is tested; I will try to do that soon.
